from time import sleep

for i in range(10):
    print("💃💃💃💃💃💃💃💃💃💃💃💃💃💃💃💃💃🌮🌮🌮🌮🌮🌮🌮🌮🌮🌮🌮🌮🌮🌮🌮🌮🌮✊✊✊✊✊✊✊✊✊✊✊✊✊✊✊✊✊✊")
sleep(3)
print ("Welcome💃,")
sleep(1)
print("to🌮")
sleep(1)
print("the✊")
sleep(1)
print("dancing💃💃")
sleep(1)
print("taco🌮🌮")
sleep(1)
print("revolution✊✊!!!!!!!")
sleep(2)
print("Here are our latest followers:")
sleep(2)
print("JOSEPH🍚,")
sleep(1)
print("MUNEEB👋🏿,")
sleep(1)
print("CASPAR👋🐱,")
sleep(1)
print("LUCAS🍔,")
sleep(1)
print("RORY🥶,") 
sleep(1)
print("DANIEL🍙.")
sleep(2)
print("Now today we are having a taco dancing battle.")
sleep(2)
print(" The first contestants are JOSEPH🍚 and MUNEEB👋🏿!")
sleep(2)
print("ROUND 1 JOSEPH🍚 vs MUNEEB👋🏿: JOSEPH🍚 is starting off strong with the floss, it looks like JOSEPH🍚 is going to win here but whats this MUNEEB👋🏿 IS DOING THE EDM BEATDROP DANCE??????!!!!!!")
sleep(7)
print("MUNEEB👋🏿 HAS WON!!!!")
sleep(2)
("The second contestants are DANIEL🍙 and RORY🥶")
sleep(2)
print("ROUND 2 DANIEL🍙 vs RORY🥶: DANIEL🍙 is on his knees begging for victory he probably doesnt know how to dance and RORY🥶 hasnt even shown up.....")
sleep(5)
print("DANIEL🍙 HAS WON!!!!! ")
sleep(2)
print("ROUND 3 LUCAS🍔 vs CASPAR👋🐱: LUCAS🍔 is starting off with the moonwalk along stage and has tragedly gone right of the stage, and CASPAR👋🐱 has taken it away with a dab perfectly timed with LUCAS'S🍔 fall...")
sleep(5)
print("AND CASPAR👋🐱 HAS OFFICIALLY WON!!!!!")
sleep(2)
print("Welcome to the finals where the last three contestants will be battling each other in this dance off so give it up for.........")
sleep(5)
print("DANIEL🍙, next we have the one and only MMUUNNEEEEBB👋🏿 and last but definetly not least we have CCCAAASSSPPPAAARRR👋🐱!!!!!!")
sleep(5)
print("FINAL ROUND DANIEL🍙 vs MUNEEB👋🏿 vs CASPAR👋🐱: DANIEL is repeating his tactic of praying but MUNEEB has gone straight into it with the worm and CASPAR has followed up with the cha cha slide. MUNEEB has gone all out with the orange justice MUNE  ")


for cha in s.split